config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  with_options except: :destroy do |o|
    o.resources :customers do
      o.resources :transactions, only: [:new, :create]
    end
    o.resources :transactions, only: [:show, :index, :edit, :update]
    o.resources :currency_pairs
    o.resources :rates
    o.resources :currencies
    o.resources :cities
    o.resources :states
    o.resources :countries
    o.resources :users
    o.resources :sessions
  end

  get 'till', to: 'till#index', as: 'till'
  get 'chart', to: 'customers#chart', as: 'chart'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/controllers/till_controller.rb
class TillController < ApplicationController
  before_filter :authorize
  def index
  	@user_transactions = Transaction.find_by_sql(["SELECT * FROM transactions WHERE user_id = ? AND created_at >= ?", current_user.id, Time.zone.now.beginning_of_day] )
  end
end

app/views/till/index.html.erb
<h3 class="page-header">
  Till &#8226; <%= Time.now.strftime("%d/%m/%Y") %>
</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Transaction ID</th>
      <th>Customer</th>
      <th>From Currency</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @user_transactions.each do |t| %>
      <tr>
        <td><%= t.id %></td>
        <td><%= gravatar_tag t.customer.email, size: 20 %> &#8226; <%= link_to t.customer.full_name, customer_path(t.customer) %></td>
        <td><%= Currency.find_by_id(t.fr_ccy_id).iso %> <%= t.fr_amount %></td>
        <td><%=t.created_at.strftime("%I:%M%p")%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<div class="row">
  <div class="col-md-4">
    <table class= "table table-condensed">
      <tr>
        <td class="info text-center">
          <b>Totals</b>
        </td>
      </tr>
      <% fr_ccy = Transaction.where("user_id = :uid AND created_at >= :date", {uid: current_user.id, date: Time.zone.now.beginning_of_day}).select(:fr_ccy_id).distinct%>
      <% fr_ccy.each do |w| %>
        <tr>
          <td>
            <b><%= Currency.find_by_id(w.fr_ccy_id).iso%></b>
            <%=Transaction.where("fr_ccy_id = :fr AND user_id = :uid AND created_at >= :date", {fr: w.fr_ccy_id, uid: current_user.id, date: Time.zone.now.beginning_of_day}).sum('fr_amount')%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>