config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  with_options except: :destroy do |o|
    o.resources :customers do
      o.resources :transactions, only: [:new, :create]
    end
    o.resources :transactions, only: [:show, :index, :edit, :update]
    o.resources :currency_pairs
    o.resources :rates
    o.resources :currencies
    o.resources :cities
    o.resources :states
    o.resources :countries
    o.resources :users
    o.resources :sessions
  end

  get 'till', to: 'till#index', as: 'till'
  get 'chart', to: 'customers#chart', as: 'chart'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

	has_paper_trail

	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_presence_of :sex
	validates_presence_of :country_id

	has_many :transactions
	belongs_to :country

	def self.search(search)
		if search
			where([ "first_name || last_name LIKE ?", "%#{search}%" ])
		else
			all
		end
	end

	def full_name
		"#{first_name } #{last_name}"
	end

	# scope :order_total
	
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authorize
  before_action :set_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.search(params[:search])
    @customers = @customers.paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def chart
  end

  def create
    @customer = Customer.new(customer_params)
    id = @customer
    @customer.country_name = Country.find_by_id(id.country_id).name
    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.' 
    else
      render :new 
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.' 
    else
      render :edit 
    end
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end


    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :sex, :profile_picture, :dob, :country_id, :email, :phone )
    end
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer, :html=> { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  
  <%= f.error_notification %>

    <%= f.input :first_name %>

    <%= f.input :last_name %>

    <%= f.input :sex %>

    <%= f.input :dob %>

    <%= f.input :country_id, :collection => Country.all, :label_method => :name, :value_method => :id, :label => "Country" ,:include_blank => true %>

    <%= f.input :email %>

    <%= f.input :phone %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit "Submit", class: "btn btn-default" %>

<% end %>

app/views/customers/chart.html.erb
<h3 class="page-header">
 	Chart <small>Customer</small>
</h3>
<br>
<%= geo_chart Customer.group(:country_name).count %>

app/views/customers/edit.html.erb
<h3 class="page-header">
  Edit <small><%= @customer.full_name %> </small>
</h3>

<%= render 'form' %>
		
		|
		<%= link_to "Back", :back, :class => "btn btn-default" %>
	</div>
</div>

app/views/customers/index.html.erb
<%= form_tag customers_path, :class => 'form-horizontal', :role => 'form', method: :get do %>
  <div class="input-group">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Type your search..." %>
    <span class="input-group-btn">
      <%= submit_tag "Go!", class: "btn btn-default" %>
    </span>
  </div>
<% end %>
<h3 class="page-header">
  Customers <span class="badge"><%= Customer.count %></span>
  <div class="pull-right">
    <%= link_to chart_path do %>
      <i class="fa fa-bar-chart"></i>
    <% end %>
    &#8226;
    <%= link_to new_customer_path do %>
      <i class="fa fa-plus-circle"></i>
    <% end %>
  </div>
</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Sex</th>
      <th>DOB</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |c| %>
      <tr>
        <td><%= gravatar_tag c.email, size: 20 %> &#8226; <%= link_to c.full_name.titleize, c %></td>
        <td><%= c.sex.titleize %></td>
        <td><%= c.dob %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @customers_pagination, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to "Back", :back, :class => "btn btn-default" %>

app/views/customers/new.html.erb
<h3 class="page-header">
  New <small><%= @customer.class %> </small>
</h3>

<%= render 'form' %>

app/views/customers/show.html.erb
<h3 class="page-header">
  <% if @customer.sex == "F" %>
    <i class="fa fa-female fa-x2"></i>
  <% else %>
    <i class="fa fa-male fa-x2"></i>
  <% end %>
  &#8226;
  <%= @customer.full_name.titleize %>
  <small>
    <%= @customer.class %>
  </small>
  <div class="pull-right">
    <%= link_to new_customer_transaction_path(@customer) do %>
      <i class="fa fa-money"></i>
    <% end %>
    &#8226;
    <%= link_to edit_customer_path(@customer) do %>
      <i class="fa fa-pencil"></i>
    <% end %>
  </div>
</h3>
<div class="row">
  <div class="col-md-2">
    <a href="#" class="thumbnail">
      <%= gravatar_tag @customer.email, size: 170 %>
    </a>
  </div>
  <div class="col-md-3">
    <table class="table table-condensed">
      <tr>
        <td>
          <i class="fa fa-gift"></i>
          <%= @customer.dob %>
        </td>
      </tr>
      <tr>
        <td>
          <i class="fa fa-globe"></i>
          <%= Country.find_by_id(@customer.country_id).nationality %>
        </td>
      </tr>
      <tr>
        <td>
          <i class="fa fa-envelope"></i>
          <% if @customer.email? %>
            <%=  @customer.email %>
          <% else %>
            No E-Mail
          <% end %>
        </td>  
      </tr>
      <tr>
        <td>
          <i class="fa fa-phone"></i>
          <% if @customer.phone? %>
            <%= @customer.phone %>
          <% else %>
            No Phone
          <% end %>
        </td>  
      </tr>
    </table>
  </div>
  <div class="col-md-5 pull-right">
    <table class="table table-condensed">
      <thead>
        <th class="text-center">ID</th>
        <th class="text-center">Date</th>
        <th class="text-center">Currency Pair</th>
        <th class="text-center">To Amount</th>
      </thead>
      <tbody class="text-center">
        <% @customer.transactions.each do |t| %>
          <tr>
            <td>
              <%= link_to t.id, t %>
            </td>
            <td>
              <%= t.created_at.strftime("%d/%m/%y") %>
            </td>
            <td>
              <%= CurrencyPair.find_by_id(t.currency_pair_id).ccy_pair_iso %>
            </td>
            <td>
              <%= t.fr_amount %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-3 pull-right"></div>
  <div class="col-md-2 pull-right">
    <table class= "table table-condensed">
      <tr>
        <td class="info text-center">
          <b>Total sent</b>
        </td>
      </tr>
      <% fr_ccy = Transaction.where("customer_id = :cid", {cid: @customer.id}).select(:fr_ccy_id).distinct %>
      <% fr_ccy.each do |w| %>
        <tr>
          <td>
            <b><%= Currency.find_by_id(w.fr_ccy_id).iso%> </b>
            <%=Transaction.where("fr_ccy_id = :fr", {fr: w.fr_ccy_id}).sum('fr_amount')%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <%= link_to 'Edit', edit_customer_path(@customer), :class => "btn btn-default" %>
    |
    <%= link_to "Back", :back, :class => "btn btn-default" %>
  </div>
</div>      